# Start running playbook

- name: test tc_fail_mode_module
  connection: local
  hosts: localhost
  tasks:
    - name: run the tc fail mode module
      tc_fail_mode_module:
        interface: enp0s3
        withheld_period: 5
      become: true
      become_method: sudo
      async: 10
      poll: 0
